// AUTO-GENERATED by `npm run train` (src/core/ml/train.ts). Do not edit by hand.
// Logistic-regression weights for the false-positive classifier.

import type { FEATURE_NAMES } from './features';

export interface ClassifierModel {
  featureNames: typeof FEATURE_NAMES;
  weights: number[];
  threshold: number;
  trainAccuracy: number;
}

export const MODEL: ClassifierModel = {
  featureNames: ["bias","rule_is_secret","rule_is_http","severity","in_test_path","secret_entropy","secret_length","secret_placeholder","secret_low_diversity","secret_example_host","env_lookup","http_namespace_url"] as unknown as typeof FEATURE_NAMES,
  weights: [3.2222,-1.6209,-0.9956,0.1668,-4.3251,0.1889,0.8204,-4.9623,-0.6202,0,-3.7888,-4.2294],
  threshold: 0.5,
  trainAccuracy: 1,
};
