// Security rules based on OWASP Top 10:2025 A04 (Cryptographic Failures)
// and A07 (Authentication Failures) from the master's thesis.

export type Severity = 'critical' | 'high' | 'medium' | 'low';
export type OwaspCategory = 'A01' | 'A03' | 'A04' | 'A07';

export interface SecurityRule {
  id: string;
  name: string;
  /** Regex tested against each line (flags: gi). Use named groups to highlight a sub-match. */
  pattern: RegExp;
  /** VS Code languageId values */
  languages: string[];
  severity: Severity;
  cwe: string;
  owasp: OwaspCategory;
  message: string;
  description: string;
  recommendation: string;
  /** Optional safer replacement for code-action quick-fix */
  fix?: { label: string; replacement: string };
}

// ---------------------------------------------------------------------------
// A04 — Cryptographic Failures
// ---------------------------------------------------------------------------

const A04_JS_TS: SecurityRule[] = [
  {
    id: 'crypto-md5-hash',
    name: 'Слабый хеш: MD5',
    pattern: /createHash\s*\(\s*['"`]md5['"`]\s*\)/gi,
    languages: ['javascript', 'typescript'],
    severity: 'critical',
    cwe: 'CWE-327',
    owasp: 'A04',
    message: 'MD5 криптографически взломан — не используйте для хеширования (CWE-327)',
    description:
      'MD5 уязвим к коллизиям и атакам с предобразом. Скорость перебора составляет ~10 млрд хешей/сек на GPU (RTX 4090). Категорически не подходит для хранения паролей.',
    recommendation:
      'Для паролей: bcrypt (cost ≥ 12), Argon2id (m=65536, t=3, p=4) или PBKDF2-HMAC-SHA256 (≥ 600 000 итераций). Для данных: SHA-256 или SHA-512.',
    fix: { label: 'Заменить на SHA-256', replacement: "createHash('sha256')" },
  },
  {
    id: 'crypto-sha1-hash',
    name: 'Слабый хеш: SHA-1',
    pattern: /createHash\s*\(\s*['"`]sha1['"`]\s*\)/gi,
    languages: ['javascript', 'typescript'],
    severity: 'critical',
    cwe: 'CWE-327',
    owasp: 'A04',
    message: 'SHA-1 официально сломан (атака SHAttered, 2017) — не используйте (CWE-327)',
    description:
      'В 2017 г. была продемонстрирована первая практическая коллизия SHA-1 (shattered.io). Стандарты NIST и CA/Browser Forum запрещают его использование.',
    recommendation: 'Используйте SHA-256 или SHA-512: createHash(\'sha256\')',
    fix: { label: 'Заменить на SHA-256', replacement: "createHash('sha256')" },
  },
  {
    id: 'crypto-md5-require',
    name: 'Импорт MD5-библиотеки',
    pattern: /require\s*\(\s*['"`]md5['"`]\s*\)/gi,
    languages: ['javascript', 'typescript'],
    severity: 'critical',
    cwe: 'CWE-327',
    owasp: 'A04',
    message: 'Импорт MD5-библиотеки — алгоритм криптографически небезопасен (CWE-327)',
    description: 'Использование отдельной md5-библиотеки указывает на применение взломанного алгоритма.',
    recommendation: 'Используйте встроенный crypto.createHash(\'sha256\') или Web Crypto API.',
  },
  {
    id: 'crypto-math-random',
    name: 'Слабый ГПСЧ: Math.random()',
    pattern: /Math\.random\s*\(\s*\)/g,
    languages: ['javascript', 'typescript'],
    severity: 'high',
    cwe: 'CWE-338',
    owasp: 'A04',
    message: 'Math.random() не является криптографически стойким ГПСЧ (CWE-338)',
    description:
      'Math.random() использует xorshift128+. Seed восстанавливается за доли секунды при наличии 2–3 последовательных значений. Нельзя использовать для токенов, ключей и nonce.',
    recommendation: 'Используйте crypto.getRandomValues(new Uint8Array(32)) или crypto.randomUUID().',
    fix: { label: 'Заменить на crypto.getRandomValues()', replacement: 'crypto.getRandomValues(new Uint32Array(1))[0] / 0xFFFFFFFF' },
  },
  {
    id: 'crypto-aes-ecb',
    name: 'Режим AES-ECB',
    pattern: /(?:['"`]AES[/-]ECB['"`]|MODE_ECB|AES\.ECB)/gi,
    languages: ['javascript', 'typescript'],
    severity: 'high',
    cwe: 'CWE-327',
    owasp: 'A04',
    message: 'AES в режиме ECB раскрывает структуру открытого текста («ECB Penguin») (CWE-327)',
    description:
      'ECB шифрует каждый блок независимо: одинаковые блоки открытого текста дают одинаковые блоки шифртекста. Позволяет выявить паттерны без знания ключа.',
    recommendation: 'Используйте AES-256-GCM (AEAD): обеспечивает конфиденциальность и целостность одновременно.',
  },
  {
    id: 'crypto-des',
    name: 'Слабый алгоритм: DES / 3DES',
    pattern: /(?:\bDES\b|\bTripleDES\b|\b3DES\b|['"`]DES['"`]|['"`]3DES['"`]|['"`]TripleDES['"`])/gi,
    languages: ['javascript', 'typescript'],
    severity: 'critical',
    cwe: 'CWE-327',
    owasp: 'A04',
    message: 'DES/3DES устарели и уязвимы (SWEET32, малый ключ) (CWE-327)',
    description: 'DES имеет 56-битный ключ (брутфорс за часы). 3DES уязвим к атаке SWEET32 и официально выведен из использования NIST в 2023 г.',
    recommendation: 'Используйте AES-256-GCM.',
  },
  {
    id: 'crypto-rc4',
    name: 'Слабый алгоритм: RC4',
    pattern: /\bRC4\b|\bARC4\b/gi,
    languages: ['javascript', 'typescript'],
    severity: 'critical',
    cwe: 'CWE-327',
    owasp: 'A04',
    message: 'RC4 имеет известные статистические слабости и запрещён в TLS (RFC 7465) (CWE-327)',
    description: 'RC4 уязвим к атакам Bar Mitzvah, Royal Holloway и другим. Запрещён в TLS (RFC 7465) с 2015 г.',
    recommendation: 'Используйте AES-256-GCM или ChaCha20-Poly1305.',
  },
  {
    id: 'crypto-weak-rsa-key',
    name: 'Слабый ключ RSA: < 2048 бит',
    pattern: /(?:modulusLength\s*:\s*(?:512|768|1024)|generateKeyPair[^;]*['"](512|768|1024)['"])/gi,
    languages: ['javascript', 'typescript'],
    severity: 'high',
    cwe: 'CWE-326',
    owasp: 'A04',
    message: 'Длина ключа RSA меньше 2048 бит недостаточна для безопасности (CWE-326)',
    description: 'Ключи RSA ≤ 1024 бит могут быть факторизованы. NIST рекомендует минимум 2048 бит до 2030 г., 3072+ бит после.',
    recommendation: 'Используйте modulusLength: 4096 или переходите на ECDSA (curve P-256 или Ed25519).',
  },
  {
    id: 'crypto-hardcoded-secret',
    name: 'Hardcoded-секрет в коде',
    pattern: /(?:password|passwd|secret|api_?key|apikey|auth_?token|private_?key|jwt_?secret)\s*[=:]\s*['"`][^'"`\s]{8,}['"`]/gi,
    languages: ['javascript', 'typescript'],
    severity: 'critical',
    cwe: 'CWE-798',
    owasp: 'A04',
    message: 'Hardcoded-секрет в исходном коде — будет виден в репозитории (CWE-798)',
    description: 'Секреты в коде попадают в git-историю и доступны всем, кто имеет доступ к репозиторию.',
    recommendation: 'Выносите секреты в переменные окружения (.env) или системы управления секретами (HashiCorp Vault, AWS Secrets Manager).',
  },
  {
    id: 'crypto-ssl-no-verify',
    name: 'Отключена проверка SSL-сертификата',
    pattern: /rejectUnauthorized\s*:\s*false/gi,
    languages: ['javascript', 'typescript'],
    severity: 'critical',
    cwe: 'CWE-295',
    owasp: 'A04',
    message: 'rejectUnauthorized: false отключает проверку TLS-сертификата (CWE-295)',
    description: 'Отключение проверки сертификата делает соединение уязвимым к MITM-атакам.',
    recommendation: 'Никогда не отключайте проверку сертификата в production. Используйте корректные CA-цепочки.',
  },
  {
    id: 'crypto-node-tls-reject',
    name: 'Отключена проверка TLS через env',
    pattern: /NODE_TLS_REJECT_UNAUTHORIZED\s*=\s*['"`]?0['"`]?/gi,
    languages: ['javascript', 'typescript'],
    severity: 'critical',
    cwe: 'CWE-295',
    owasp: 'A04',
    message: 'NODE_TLS_REJECT_UNAUTHORIZED=0 глобально отключает TLS-верификацию (CWE-295)',
    description: 'Этот флаг отключает проверку сертификатов для всего Node.js процесса.',
    recommendation: 'Удалите эту строку. Для работы с самоподписанными сертификатами используйте опцию ca: с корневым CA.',
  },
  {
    id: 'crypto-http-url',
    name: 'HTTP вместо HTTPS',
    pattern: /['"`]http:\/\/(?!localhost|127\.0\.0\.1|0\.0\.0\.0)[^'"`\s]{5,}/gi,
    languages: ['javascript', 'typescript'],
    severity: 'medium',
    cwe: 'CWE-319',
    owasp: 'A04',
    message: 'Использование HTTP вместо HTTPS — данные передаются в открытом виде (CWE-319)',
    description: 'HTTP не обеспечивает конфиденциальности и целостности данных. Возможны MITM-атаки и перехват сессий.',
    recommendation: 'Используйте HTTPS. Настройте HSTS (Strict-Transport-Security: max-age=63072000; includeSubDomains; preload).',
  },
];

const A04_PYTHON: SecurityRule[] = [
  {
    id: 'py-crypto-md5',
    name: 'Слабый хеш: MD5 (Python)',
    pattern: /hashlib\.md5\s*\(|hashlib\.new\s*\(\s*['"`]md5['"`]/gi,
    languages: ['python'],
    severity: 'critical',
    cwe: 'CWE-327',
    owasp: 'A04',
    message: 'hashlib.md5() — MD5 криптографически взломан (CWE-327)',
    description: 'MD5 уязвим к коллизиям. Не использовать для хранения паролей или проверки целостности.',
    recommendation: 'Для паролей: passlib с bcrypt/argon2. Для данных: hashlib.sha256() или hashlib.sha512().',
    fix: { label: 'Заменить на SHA-256', replacement: 'hashlib.sha256(' },
  },
  {
    id: 'py-crypto-sha1',
    name: 'Слабый хеш: SHA-1 (Python)',
    pattern: /hashlib\.sha1\s*\(|hashlib\.new\s*\(\s*['"`]sha1['"`]/gi,
    languages: ['python'],
    severity: 'critical',
    cwe: 'CWE-327',
    owasp: 'A04',
    message: 'hashlib.sha1() — SHA-1 официально сломан (атака SHAttered) (CWE-327)',
    description: 'SHA-1 сломан с 2017 г. Практическая коллизия была продемонстрирована Google/CWI.',
    recommendation: 'Используйте hashlib.sha256() или hashlib.sha3_256().',
    fix: { label: 'Заменить на SHA-256', replacement: 'hashlib.sha256(' },
  },
  {
    id: 'py-prng-random',
    name: 'Слабый ГПСЧ: random (Python)',
    pattern: /\brandom\.(?:seed|random|randint|randrange|choice|shuffle)\s*\(/gi,
    languages: ['python'],
    severity: 'high',
    cwe: 'CWE-338',
    owasp: 'A04',
    message: 'Модуль random не является криптографически стойким (CWE-338)',
    description:
      'Python random использует Mersenne Twister — предсказуем, если наблюдатель видит достаточно выходных значений. Нельзя использовать для токенов.',
    recommendation: 'Используйте модуль secrets: secrets.token_hex(32), secrets.token_urlsafe() или os.urandom().',
    fix: { label: 'Заменить на secrets', replacement: 'secrets.token_hex(' },
  },
  {
    id: 'py-aes-ecb',
    name: 'Режим AES-ECB (Python)',
    pattern: /AES\.MODE_ECB|['"`]AES-ECB['"`]/gi,
    languages: ['python'],
    severity: 'high',
    cwe: 'CWE-327',
    owasp: 'A04',
    message: 'AES в режиме ECB раскрывает структуру данных (CWE-327)',
    description: 'ECB шифрует каждый блок независимо, что позволяет обнаружить повторяющиеся блоки без ключа.',
    recommendation: 'Используйте AES.MODE_GCM или AES.MODE_SIV (PyCryptodome) для аутентифицированного шифрования.',
  },
  {
    id: 'py-des',
    name: 'Слабый алгоритм: DES (Python)',
    pattern: /(?:DES\.new|DES3\.new|from\s+Crypto\.Cipher\s+import\s+DES)/gi,
    languages: ['python'],
    severity: 'critical',
    cwe: 'CWE-327',
    owasp: 'A04',
    message: 'DES/3DES устарели и небезопасны (CWE-327)',
    description: 'DES имеет 56-битный ключ, 3DES уязвим к SWEET32.',
    recommendation: 'Замените на AES-256-GCM (from Crypto.Cipher import AES; AES.new(key, AES.MODE_GCM)).',
  },
  {
    id: 'py-rc4',
    name: 'Слабый алгоритм: RC4/ARC4 (Python)',
    pattern: /ARC4\.new\s*\(|from\s+Crypto\.Cipher\s+import\s+ARC4/gi,
    languages: ['python'],
    severity: 'critical',
    cwe: 'CWE-327',
    owasp: 'A04',
    message: 'RC4/ARC4 имеет известные слабости и запрещён в TLS (CWE-327)',
    description: 'RC4 уязвим к атакам Bar Mitzvah и Royal Holloway. Запрещён RFC 7465.',
    recommendation: 'Используйте AES-256-GCM или ChaCha20-Poly1305.',
  },
  {
    id: 'py-weak-rsa',
    name: 'Слабый ключ RSA (Python)',
    pattern: /RSA\.generate\s*\(\s*(?:512|768|1024)\s*\)/gi,
    languages: ['python'],
    severity: 'high',
    cwe: 'CWE-326',
    owasp: 'A04',
    message: 'Ключ RSA меньше 2048 бит недостаточен для безопасности (CWE-326)',
    description: 'RSA-1024 может быть факторизован. NIST требует минимум 2048 бит.',
    recommendation: 'Используйте RSA.generate(4096) или переходите на ECC (ec.generate_private_key(ec.SECP256R1())).',
  },
  {
    id: 'py-ssl-verify-false',
    name: 'SSL-верификация отключена (Python)',
    pattern: /verify\s*=\s*False|CERT_NONE|ssl_verify\s*=\s*False/gi,
    languages: ['python'],
    severity: 'critical',
    cwe: 'CWE-295',
    owasp: 'A04',
    message: 'Отключена проверка SSL-сертификата — MITM-атака возможна (CWE-295)',
    description: 'verify=False или CERT_NONE позволяет атакующему перехватить и изменить HTTPS-трафик.',
    recommendation: 'Используйте корректные CA-сертификаты. В крайнем случае: verify=\'/path/to/ca-bundle.crt\'.',
  },
  {
    id: 'py-hardcoded-secret',
    name: 'Hardcoded-секрет (Python)',
    pattern: /(?:password|passwd|secret|api_?key|token|private_?key)\s*=\s*['"`][^'"`\s]{8,}['"`]/gi,
    languages: ['python'],
    severity: 'critical',
    cwe: 'CWE-798',
    owasp: 'A04',
    message: 'Hardcoded-секрет в коде (CWE-798)',
    description: 'Секреты в исходном коде попадают в git-историю.',
    recommendation: 'Используйте os.environ.get(\'SECRET_KEY\') или python-dotenv.',
  },
  {
    id: 'py-http-url',
    name: 'HTTP вместо HTTPS (Python)',
    pattern: /['"`]http:\/\/(?!localhost|127\.0\.0\.1)[^'"`\s]{5,}/gi,
    languages: ['python'],
    severity: 'medium',
    cwe: 'CWE-319',
    owasp: 'A04',
    message: 'HTTP вместо HTTPS — трафик не зашифрован (CWE-319)',
    description: 'Данные передаются в открытом виде, подвержены перехвату.',
    recommendation: 'Замените http:// на https:// и настройте HSTS.',
  },
  {
    id: 'py-eval',
    name: 'Выполнение динамического кода: eval()',
    pattern: /\beval\s*\(/gi,
    languages: ['python'],
    severity: 'high',
    cwe: 'CWE-95',
    owasp: 'A03',
    message: 'eval() выполняет произвольный код — риск инъекции (CWE-95)',
    description: 'eval() с пользовательским вводом позволяет выполнить произвольный Python-код.',
    recommendation: 'Замените eval() на безопасные альтернативы: ast.literal_eval() для данных, json.loads() для JSON.',
  },
  {
    id: 'py-pickle',
    name: 'Небезопасная десериализация: pickle',
    pattern: /pickle\.loads?\s*\(/gi,
    languages: ['python'],
    severity: 'critical',
    cwe: 'CWE-502',
    owasp: 'A03',
    message: 'pickle.loads() с недоверенными данными — RCE-уязвимость (CWE-502)',
    description: 'pickle может десериализовать объекты, выполняющие произвольный код при создании.',
    recommendation: 'Используйте JSON, MessagePack или другие безопасные форматы сериализации.',
  },
];

const A04_JAVA: SecurityRule[] = [
  {
    id: 'java-md5',
    name: 'Слабый хеш: MD5 (Java)',
    pattern: /MessageDigest\.getInstance\s*\(\s*["']MD5["']\s*\)/gi,
    languages: ['java'],
    severity: 'critical',
    cwe: 'CWE-327',
    owasp: 'A04',
    message: 'MessageDigest MD5 — алгоритм криптографически взломан (CWE-327)',
    description: 'MD5 уязвим к коллизиям. Нельзя использовать для паролей или цифровых подписей.',
    recommendation: 'Для паролей: BCrypt или Argon2 (Spring Security). Для хешей данных: SHA-256.',
    fix: { label: 'Заменить на SHA-256', replacement: 'MessageDigest.getInstance("SHA-256")' },
  },
  {
    id: 'java-sha1',
    name: 'Слабый хеш: SHA-1 (Java)',
    pattern: /MessageDigest\.getInstance\s*\(\s*["']SHA-?1["']\s*\)/gi,
    languages: ['java'],
    severity: 'critical',
    cwe: 'CWE-327',
    owasp: 'A04',
    message: 'MessageDigest SHA-1 — алгоритм официально сломан (CWE-327)',
    description: 'SHA-1 запрещён CA/Browser Forum для подписи сертификатов с 2017 г.',
    recommendation: 'Используйте MessageDigest.getInstance("SHA-256") или MessageDigest.getInstance("SHA-512").',
    fix: { label: 'Заменить на SHA-256', replacement: 'MessageDigest.getInstance("SHA-256")' },
  },
  {
    id: 'java-random',
    name: 'Слабый ГПСЧ: new Random() (Java)',
    pattern: /\bnew\s+Random\s*\(\s*\)/g,
    languages: ['java'],
    severity: 'high',
    cwe: 'CWE-338',
    owasp: 'A04',
    message: 'java.util.Random не является криптографически стойким (CWE-338)',
    description: 'java.util.Random использует линейный конгруэнтный генератор — предсказуем.',
    recommendation: 'Используйте java.security.SecureRandom для криптографических целей.',
    fix: { label: 'Заменить на SecureRandom', replacement: 'new SecureRandom()' },
  },
  {
    id: 'java-aes-ecb',
    name: 'Режим AES-ECB (Java)',
    pattern: /Cipher\.getInstance\s*\(\s*["']AES["']\s*\)|["']AES\/ECB/gi,
    languages: ['java'],
    severity: 'high',
    cwe: 'CWE-327',
    owasp: 'A04',
    message: 'AES/ECB или Cipher.getInstance("AES") использует ECB по умолчанию (CWE-327)',
    description: 'Cipher.getInstance("AES") использует ECB режим по умолчанию в JCE.',
    recommendation: 'Используйте Cipher.getInstance("AES/GCM/NoPadding") для аутентифицированного шифрования.',
    fix: { label: 'Заменить на AES/GCM', replacement: 'Cipher.getInstance("AES/GCM/NoPadding")' },
  },
  {
    id: 'java-des',
    name: 'Слабый алгоритм: DES/3DES (Java)',
    pattern: /Cipher\.getInstance\s*\(\s*["'](?:DES|DESede|3DES)[/"']/gi,
    languages: ['java'],
    severity: 'critical',
    cwe: 'CWE-327',
    owasp: 'A04',
    message: 'DES/3DES устарели и небезопасны (CWE-327)',
    description: 'DES — 56-битный ключ. 3DES уязвим к SWEET32 и выведен NIST в 2023 г.',
    recommendation: 'Используйте Cipher.getInstance("AES/GCM/NoPadding").',
  },
  {
    id: 'java-weak-rsa',
    name: 'Слабый ключ RSA (Java)',
    pattern: /\.initialize\s*\(\s*(?:512|768|1024)\s*\)/gi,
    languages: ['java'],
    severity: 'high',
    cwe: 'CWE-326',
    owasp: 'A04',
    message: 'Ключ RSA/DSA менее 2048 бит недостаточен (CWE-326)',
    description: 'NIST требует минимум 2048 бит для RSA/DSA до 2030 г.',
    recommendation: 'Используйте .initialize(4096) или перейдите на EC-ключи (KeyPairGenerator.getInstance("EC")).',
  },
  {
    id: 'java-hardcoded-secret',
    name: 'Hardcoded-секрет (Java)',
    pattern: /(?:password|passwd|secret|apiKey|token|privateKey)\s*=\s*["'][^"'\s]{8,}["']/gi,
    languages: ['java'],
    severity: 'critical',
    cwe: 'CWE-798',
    owasp: 'A04',
    message: 'Hardcoded-секрет в исходном коде (CWE-798)',
    description: 'Секреты в коде попадают в систему контроля версий.',
    recommendation: 'Используйте переменные окружения, Spring Cloud Config или HashiCorp Vault.',
  },
  {
    id: 'java-http-url',
    name: 'HTTP вместо HTTPS (Java)',
    pattern: /["']http:\/\/(?!localhost|127\.0\.0\.1)[^"'\s]{5,}/gi,
    languages: ['java'],
    severity: 'medium',
    cwe: 'CWE-319',
    owasp: 'A04',
    message: 'HTTP вместо HTTPS — данные передаются в открытом виде (CWE-319)',
    description: 'Без TLS трафик может быть перехвачен.',
    recommendation: 'Используйте HTTPS и настройте HSTS.',
  },
];

const A04_GO: SecurityRule[] = [
  {
    id: 'go-md5',
    name: 'Слабый хеш: MD5 (Go)',
    pattern: /\bmd5\.(?:New|Sum)\s*\(|"crypto\/md5"/gi,
    languages: ['go'],
    severity: 'critical',
    cwe: 'CWE-327',
    owasp: 'A04',
    message: 'crypto/md5 — MD5 криптографически взломан (CWE-327)',
    description: 'MD5 не должен использоваться в криптографических целях.',
    recommendation: 'Используйте crypto/sha256 или golang.org/x/crypto/argon2 для паролей.',
  },
  {
    id: 'go-sha1',
    name: 'Слабый хеш: SHA-1 (Go)',
    pattern: /\bsha1\.(?:New|Sum)\s*\(|"crypto\/sha1"/gi,
    languages: ['go'],
    severity: 'critical',
    cwe: 'CWE-327',
    owasp: 'A04',
    message: 'crypto/sha1 — SHA-1 официально сломан (CWE-327)',
    description: 'SHA-1 запрещён для подписи и TLS-сертификатов.',
    recommendation: 'Используйте sha256.New() из crypto/sha256.',
  },
  {
    id: 'go-math-rand',
    name: 'Слабый ГПСЧ: math/rand (Go)',
    pattern: /"math\/rand"|rand\.(?:Intn|Int|Float64|Read)\s*\(/gi,
    languages: ['go'],
    severity: 'high',
    cwe: 'CWE-338',
    owasp: 'A04',
    message: 'math/rand не является криптографически стойким ГПСЧ (CWE-338)',
    description: 'math/rand предсказуем и не должен использоваться для токенов, ключей или nonce.',
    recommendation: 'Используйте crypto/rand: rand.Read(b) или rand.Int(rand.Reader, max).',
  },
  {
    id: 'go-tls-insecure',
    name: 'Отключена TLS-верификация (Go)',
    pattern: /InsecureSkipVerify\s*:\s*true/gi,
    languages: ['go'],
    severity: 'critical',
    cwe: 'CWE-295',
    owasp: 'A04',
    message: 'InsecureSkipVerify: true отключает проверку TLS-сертификата (CWE-295)',
    description: 'Соединение уязвимо к MITM-атакам.',
    recommendation: 'Удалите InsecureSkipVerify или настройте RootCAs с корректным CA-пулом.',
  },
  {
    id: 'go-weak-rsa',
    name: 'Слабый ключ RSA (Go)',
    pattern: /rsa\.GenerateKey\s*\([^,]+,\s*(?:512|768|1024)\s*\)/gi,
    languages: ['go'],
    severity: 'high',
    cwe: 'CWE-326',
    owasp: 'A04',
    message: 'Ключ RSA менее 2048 бит (CWE-326)',
    description: 'NIST требует минимум 2048 бит.',
    recommendation: 'Используйте rsa.GenerateKey(rand.Reader, 4096) или ecdsa.GenerateKey(elliptic.P256(), rand.Reader).',
  },
  {
    id: 'go-hardcoded-secret',
    name: 'Hardcoded-секрет (Go)',
    pattern: /(?:password|secret|apiKey|token|privateKey)\s*:?=\s*"[^"\s]{8,}"/gi,
    languages: ['go'],
    severity: 'critical',
    cwe: 'CWE-798',
    owasp: 'A04',
    message: 'Hardcoded-секрет в исходном коде (CWE-798)',
    description: 'Секреты в коде попадают в репозиторий.',
    recommendation: 'Используйте os.Getenv("SECRET") или github.com/spf13/viper.',
  },
  {
    id: 'go-http-url',
    name: 'HTTP вместо HTTPS (Go)',
    pattern: /"http:\/\/(?!localhost|127\.0\.0\.1)[^"\s]{5,}"/gi,
    languages: ['go'],
    severity: 'medium',
    cwe: 'CWE-319',
    owasp: 'A04',
    message: 'HTTP вместо HTTPS (CWE-319)',
    description: 'Данные передаются в открытом виде.',
    recommendation: 'Используйте HTTPS.',
  },
];

const A04_PHP: SecurityRule[] = [
  {
    id: 'php-md5',
    name: 'Слабый хеш: md5() (PHP)',
    pattern: /\bmd5\s*\(\s*\$/gi,
    languages: ['php'],
    severity: 'critical',
    cwe: 'CWE-327',
    owasp: 'A04',
    message: 'md5() для хеширования пользовательских данных — небезопасно (CWE-327)',
    description: 'md5() не является функцией хеширования паролей.',
    recommendation: 'Используйте password_hash($pass, PASSWORD_ARGON2ID) и password_verify().',
  },
  {
    id: 'php-sha1',
    name: 'Слабый хеш: sha1() (PHP)',
    pattern: /\bsha1\s*\(\s*\$/gi,
    languages: ['php'],
    severity: 'critical',
    cwe: 'CWE-327',
    owasp: 'A04',
    message: 'sha1() для хеширования — алгоритм сломан (CWE-327)',
    description: 'SHA-1 сломан с 2017 г.',
    recommendation: 'Используйте password_hash($pass, PASSWORD_ARGON2ID).',
  },
  {
    id: 'php-rand',
    name: 'Слабый ГПСЧ: rand() / mt_rand() (PHP)',
    pattern: /\b(?:rand|mt_rand)\s*\(/gi,
    languages: ['php'],
    severity: 'high',
    cwe: 'CWE-338',
    owasp: 'A04',
    message: 'rand()/mt_rand() не являются криптографически стойкими (CWE-338)',
    description: 'rand() и mt_rand() предсказуемы. Нельзя использовать для токенов и ключей.',
    recommendation: 'Используйте random_bytes(32) или random_int() для криптографических целей.',
  },
  {
    id: 'php-ssl-verify',
    name: 'SSL-верификация отключена (PHP)',
    pattern: /CURLOPT_SSL_VERIFYPEER\s*,\s*(?:false|0)|CURLOPT_SSL_VERIFYHOST\s*,\s*(?:false|0)/gi,
    languages: ['php'],
    severity: 'critical',
    cwe: 'CWE-295',
    owasp: 'A04',
    message: 'Отключена SSL-верификация в cURL (CWE-295)',
    description: 'CURLOPT_SSL_VERIFYPEER=false открывает возможность MITM.',
    recommendation: 'Удалите эти опции или укажите правильный CA-bundle через CURLOPT_CAINFO.',
  },
  {
    id: 'php-hardcoded-secret',
    name: 'Hardcoded-секрет (PHP)',
    pattern: /(?:\$password|\$passwd|\$secret|\$api_?key|\$token)\s*=\s*['"][^'"\s]{8,}['"]/gi,
    languages: ['php'],
    severity: 'critical',
    cwe: 'CWE-798',
    owasp: 'A04',
    message: 'Hardcoded-секрет в PHP-коде (CWE-798)',
    description: 'Секрет в коде попадёт в репозиторий.',
    recommendation: 'Используйте $_ENV или файл .env с vlucas/phpdotenv.',
  },
  {
    id: 'php-eval',
    name: 'Выполнение кода: eval() (PHP)',
    pattern: /\beval\s*\(/gi,
    languages: ['php'],
    severity: 'high',
    cwe: 'CWE-95',
    owasp: 'A03',
    message: 'eval() с пользовательским вводом — код-инъекция (CWE-95)',
    description: 'eval() выполняет произвольный PHP-код.',
    recommendation: 'Никогда не передавайте пользовательский ввод в eval(). Пересмотрите архитектуру.',
  },
  {
    id: 'php-http-url',
    name: 'HTTP вместо HTTPS (PHP)',
    pattern: /['"]http:\/\/(?!localhost|127\.0\.0\.1)[^'"\s]{5,}/gi,
    languages: ['php'],
    severity: 'medium',
    cwe: 'CWE-319',
    owasp: 'A04',
    message: 'HTTP вместо HTTPS (CWE-319)',
    description: 'Данные передаются без шифрования.',
    recommendation: 'Замените http:// на https://.',
  },
];

const A04_C_CPP: SecurityRule[] = [
  {
    id: 'c-md5',
    name: 'Слабый хеш: MD5 (C/C++)',
    pattern: /\bMD5\s*\(|\bmd5_init\s*\(|\bEVP_md5\s*\(\s*\)/gi,
    languages: ['c', 'cpp'],
    severity: 'critical',
    cwe: 'CWE-327',
    owasp: 'A04',
    message: 'MD5 криптографически взломан (CWE-327)',
    description: 'MD5 не должен использоваться для криптографических целей.',
    recommendation: 'Используйте SHA-256: EVP_sha256() или libsodium crypto_generichash().',
  },
  {
    id: 'c-sha1',
    name: 'Слабый хеш: SHA-1 (C/C++)',
    pattern: /\bSHA1\s*\(|\bEVP_sha1\s*\(\s*\)/gi,
    languages: ['c', 'cpp'],
    severity: 'critical',
    cwe: 'CWE-327',
    owasp: 'A04',
    message: 'SHA-1 официально сломан (CWE-327)',
    description: 'SHA-1 взломан в 2017 г.',
    recommendation: 'Используйте EVP_sha256() из OpenSSL.',
  },
  {
    id: 'c-rand',
    name: 'Слабый ГПСЧ: rand() (C/C++)',
    pattern: /\brand\s*\(\s*\)|\bsrand\s*\(\s*time/gi,
    languages: ['c', 'cpp'],
    severity: 'high',
    cwe: 'CWE-338',
    owasp: 'A04',
    message: 'rand() не является CSPRNG, srand(time()) с предсказуемым seed (CWE-338)',
    description: 'rand() предсказуем, srand(time()) легко воспроизводим.',
    recommendation: 'Используйте /dev/urandom, RAND_bytes() из OpenSSL или getrandom().',
  },
  {
    id: 'c-des',
    name: 'Слабый алгоритм: DES (C/C++)',
    pattern: /\bEVP_des_|\bDES_/gi,
    languages: ['c', 'cpp'],
    severity: 'critical',
    cwe: 'CWE-327',
    owasp: 'A04',
    message: 'DES устарел и небезопасен (CWE-327)',
    description: '56-битный ключ DES взламывается брутфорсом.',
    recommendation: 'Используйте EVP_aes_256_gcm().',
  },
  {
    id: 'c-rc4',
    name: 'Слабый алгоритм: RC4 (C/C++)',
    pattern: /\bRC4\s*\(|\bEVP_rc4\s*\(\s*\)/gi,
    languages: ['c', 'cpp'],
    severity: 'critical',
    cwe: 'CWE-327',
    owasp: 'A04',
    message: 'RC4 уязвим и запрещён в TLS (CWE-327)',
    description: 'Атаки Bar Mitzvah и NOMORE делают RC4 непригодным.',
    recommendation: 'Используйте AES-256-GCM или ChaCha20-Poly1305.',
  },
];

// ---------------------------------------------------------------------------
// A07 — Authentication Failures
// ---------------------------------------------------------------------------

const A07_ALL: SecurityRule[] = [
  // JWT alg:none — применимо к JS/TS/Python/Java/Go/PHP
  {
    id: 'jwt-alg-none',
    name: 'JWT: алгоритм none',
    pattern: /['"`]alg['"`]\s*:\s*['"`]none['"`]|alg\s*=\s*['"`]none['"`]|algorithm\s*[=:]\s*['"`]none['"`]/gi,
    languages: ['javascript', 'typescript', 'python', 'java', 'go', 'php'],
    severity: 'critical',
    cwe: 'CWE-347',
    owasp: 'A07',
    message: 'JWT с alg:none — токен без подписи (CVE-2015-9235, CWE-347)',
    description:
      'Если библиотека принимает alg:none, злоумышленник создаёт произвольный payload без знания секрета. CVE-2015-9235 затронул PyJWT, node-jsonwebtoken и другие популярные библиотеки.',
    recommendation:
      'Явно задавайте список допустимых алгоритмов при верификации: HS256, RS256 или ES256. Отклоняйте токены с alg:none.',
  },
  {
    id: 'jwt-weak-hmac',
    name: 'JWT: слабый HMAC-алгоритм',
    pattern: /['"`]alg['"`]\s*:\s*['"`]HS(?:1|2)56['"`]|algorithm\s*[=:]\s*['"`]HS(?:1|2)56['"`]/gi,
    languages: ['javascript', 'typescript', 'python', 'java', 'go'],
    severity: 'medium',
    cwe: 'CWE-327',
    owasp: 'A07',
    message: 'JWT: HS256 с коротким секретом уязвим к атаке hashcat (CWE-327)',
    description: 'HS256 безопасен при длинном случайном секрете, но часто используется с предсказуемыми паролями.',
    recommendation: 'Используйте секрет не менее 256 бит (32 байт) из CSPRNG. Или переходите на RS256/ES256.',
  },
  {
    id: 'jwt-hmac-rsa-confusion',
    name: 'JWT: HMAC/RSA confusion',
    pattern: /verify\s*\([^,)]+,\s*publicKey|verify\s*\([^,)]+,\s*pub_key/gi,
    languages: ['javascript', 'typescript', 'python'],
    severity: 'critical',
    cwe: 'CWE-347',
    owasp: 'A07',
    message: 'Возможная атака JWT HMAC/RSA confusion (CVE-2016-10555, CWE-347)',
    description:
      'Если передать RSA публичный ключ как HMAC-секрет, а алгоритм подменить на HS256, некоторые библиотеки принимают токен.',
    recommendation: 'Явно задавайте алгоритм при верификации. Не используйте публичный ключ как HMAC-секрет.',
  },
];

const A07_JS_TS: SecurityRule[] = [
  {
    id: 'auth-cookie-httponly',
    name: 'Cookie без HttpOnly',
    pattern: /(?:res\.cookie|document\.cookie\s*=)[^;]*(?!\bhttpOnly\b|\bhttponly\b)/gi,
    languages: ['javascript', 'typescript'],
    severity: 'high',
    cwe: 'CWE-1004',
    owasp: 'A07',
    message: 'Cookie без флага HttpOnly — уязвима к XSS-краже (CWE-1004)',
    description: 'Без HttpOnly JavaScript может читать значение cookie, что позволяет XSS-атаке украсть сессию.',
    recommendation: 'Установите httpOnly: true в параметрах cookie: res.cookie(\'session\', val, { httpOnly: true, secure: true, sameSite: \'strict\' }).',
  },
  {
    id: 'auth-cookie-secure',
    name: 'Cookie без Secure',
    pattern: /res\.cookie\s*\([^)]+\)(?!\s*.*\bsecure\b)/gi,
    languages: ['javascript', 'typescript'],
    severity: 'medium',
    cwe: 'CWE-614',
    owasp: 'A07',
    message: 'Cookie без флага Secure — может передаваться по HTTP (CWE-614)',
    description: 'Без Secure cookie может быть отправлена по незащищённому HTTP-соединению.',
    recommendation: 'Добавьте secure: true: res.cookie(\'name\', value, { secure: true }).',
  },
  {
    id: 'auth-cors-wildcard',
    name: 'CORS Wildcard',
    pattern: /['"`]Access-Control-Allow-Origin['"`]\s*[,:]\s*['"`]\*['"`]|origin\s*:\s*['"`]\*['"`]/gi,
    languages: ['javascript', 'typescript'],
    severity: 'high',
    cwe: 'CWE-942',
    owasp: 'A07',
    message: 'CORS Wildcard (*) разрешает запросы с любого домена (CWE-942)',
    description: 'Access-Control-Allow-Origin: * позволяет любому сайту делать кросс-доменные запросы к вашему API.',
    recommendation: 'Задайте конкретные допустимые домены. Используйте allowlist: origin: [\'https://yourdomain.com\'].',
  },
  {
    id: 'auth-xpoweredby',
    name: 'Утечка X-Powered-By',
    pattern: /app\.(?:enable|set)\s*\(\s*['"`]x-powered-by['"`]/gi,
    languages: ['javascript', 'typescript'],
    severity: 'low',
    cwe: 'CWE-200',
    owasp: 'A07',
    message: 'X-Powered-By раскрывает информацию о стеке (CWE-200)',
    description: 'X-Powered-By: Express/PHP/ASP.NET помогает атакующему выбрать специфичные эксплойты.',
    recommendation: 'Отключите заголовок: app.disable(\'x-powered-by\') или используйте helmet.js.',
  },
  {
    id: 'auth-no-rate-limit-comment',
    name: 'Отсутствие rate limiting',
    pattern: /(?:\/login|\/auth|\/token|\/password)['"`]\s*,\s*(?:async\s*)?\(?req/gi,
    languages: ['javascript', 'typescript'],
    severity: 'high',
    cwe: 'CWE-307',
    owasp: 'A07',
    message: 'Endpoint аутентификации без видимого rate limiting (CWE-307)',
    description:
      'Endpoint /login, /auth, /token без rate limiting уязвим к брутфорс-атакам по словарю (CWE-307). NIST SP 800-63b: не более 100 попыток до блокировки.',
    recommendation: 'Добавьте express-rate-limit или аналог: rateLimit({ windowMs: 15*60*1000, max: 10 }).',
  },
];

const A07_PYTHON_AUTH: SecurityRule[] = [
  {
    id: 'py-cors-wildcard',
    name: 'CORS Wildcard (Python)',
    pattern: /CORS_ALLOW_ALL_ORIGINS\s*=\s*True|origins\s*=\s*\[?\s*['"]\*['"]/gi,
    languages: ['python'],
    severity: 'high',
    cwe: 'CWE-942',
    owasp: 'A07',
    message: 'CORS Wildcard — запросы с любого домена разрешены (CWE-942)',
    description: 'Разрешение всех источников для CORS снижает защиту от CSRF и IDOR.',
    recommendation: 'Явно задайте список разрешённых доменов: CORS_ALLOWED_ORIGINS = [\'https://yourdomain.com\'].',
  },
  {
    id: 'py-debug-true',
    name: 'DEBUG=True в production',
    pattern: /DEBUG\s*=\s*True/gi,
    languages: ['python'],
    severity: 'high',
    cwe: 'CWE-94',
    owasp: 'A07',
    message: 'DEBUG=True раскрывает traceback и конфигурацию (CWE-94)',
    description: 'В режиме DEBUG Django/Flask показывает полный traceback, переменные окружения и настройки.',
    recommendation: 'Установите DEBUG = os.environ.get(\'DEBUG\', \'False\') == \'True\'.',
  },
];

// ---------------------------------------------------------------------------
// Export combined rules list
// ---------------------------------------------------------------------------

export const SECURITY_RULES: readonly SecurityRule[] = [
  ...A04_JS_TS,
  ...A04_PYTHON,
  ...A04_JAVA,
  ...A04_GO,
  ...A04_PHP,
  ...A04_C_CPP,
  ...A07_ALL,
  ...A07_JS_TS,
  ...A07_PYTHON_AUTH,
];

export const SEVERITY_ORDER: Record<Severity, number> = {
  critical: 0,
  high: 1,
  medium: 2,
  low: 3,
};

export function getRuleById(id: string): SecurityRule | undefined {
  return SECURITY_RULES.find((r) => r.id === id);
}

export function getRulesForLanguage(languageId: string): SecurityRule[] {
  return SECURITY_RULES.filter((r) => r.languages.includes(languageId));
}

/** Canonical OWASP Top 10:2025 page for a category. */
export function owaspUrl(category: OwaspCategory): string {
  const map: Record<string, string> = {
    A01: 'https://owasp.org/Top10/2025/A01_2025-Broken_Access_Control/',
    A03: 'https://owasp.org/Top10/2025/A05_2025-Injection/',
    A04: 'https://owasp.org/Top10/2025/A04_2025-Cryptographic_Failures/',
    A07: 'https://owasp.org/Top10/2025/A07_2025-Authentication_Failures/',
  };
  return map[category] ?? 'https://owasp.org/Top10/2025/';
}

/** Canonical MITRE CWE definition page (e.g. "CWE-327" → …/327.html). */
export function cweUrl(cwe: string): string {
  return `https://cwe.mitre.org/data/definitions/${cwe.replace('CWE-', '')}.html`;
}
